apiVersion: v1
kind: Service
metadata:
  name: vectis
  labels:
    app.kubernetes.io/name: vectis
    app.kubernetes.io/component: server
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: vectis
  ports:
    - name: http
      port: 80
      targetPort: http
