# Vectis server (spike). Commercial audit is opt-in and OFF by default, so a
# stock OSS deployment boots on the community floor. A licensed deployment that
# also has the enterprise plugin JAR present sets this to true.
vectis.enterprise.audit.enabled=false

quarkus.http.port=8080
quarkus.banner.enabled=false
